version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: bookmarker_app
    restart: unless-stopped
    working_dir: /var/www/html
    env_file:
      - .env
    volumes:
      - .:/var/www/html
      - storage:/var/www/html/storage
    depends_on:
      - postgres
      - redis
    networks:
      - laravel_network

  nginx:
    image: nginx:latest
    container_name: bookmarker_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_network

  postgres:
    image: postgis/postgis:16-3.4-alpine
    container_name: bookmarker_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel_network

  redis:
    image: redis:7.2.4-alpine3.19
    container_name: bookmarker_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning --requirepass redispassword
    networks:
      - laravel_network
    volumes:
      - ./redisdatabase/redis/redis:/var/lib/redis
      - ./redisdatabase/redis/redis-config:/usr/local/etc/redis/redis.conf
      - ./redisdatabase/redis/data:/data

volumes:
  pgdata:
  storage:

networks:
  laravel_network:
    driver: bridge
